//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixR_20.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SixR_20.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid literal type..
        /// </summary>
        internal static string AA0010001 {
            get {
                return ResourceManager.GetString("AA0010001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefied variable name..
        /// </summary>
        internal static string AA0010002 {
            get {
                return ResourceManager.GetString("AA0010002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of range..
        /// </summary>
        internal static string AA0010003 {
            get {
                return ResourceManager.GetString("AA0010003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Operator can only be applied on numerics..
        /// </summary>
        internal static string AA0010004 {
            get {
                return ResourceManager.GetString("AA0010004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Operator can only be applied on boolean..
        /// </summary>
        internal static string AA0010005 {
            get {
                return ResourceManager.GetString("AA0010005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplicative Operators can only be applied on numerics..
        /// </summary>
        internal static string AA0010006 {
            get {
                return ResourceManager.GetString("AA0010006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additive Operators can only be applied on numerics..
        /// </summary>
        internal static string AA0010007 {
            get {
                return ResourceManager.GetString("AA0010007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND Operator can only be applied on boolean..
        /// </summary>
        internal static string AA0010008 {
            get {
                return ResourceManager.GetString("AA0010008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XOR Operator can only be applied on boolean..
        /// </summary>
        internal static string AA0010009 {
            get {
                return ResourceManager.GetString("AA0010009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OR Operator can only be applied on boolean..
        /// </summary>
        internal static string AA0010010 {
            get {
                return ResourceManager.GetString("AA0010010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relational and Equality Operators must be applied to objects with same types..
        /// </summary>
        internal static string AA0010011 {
            get {
                return ResourceManager.GetString("AA0010011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefiend Operator..
        /// </summary>
        internal static string AA0010012 {
            get {
                return ResourceManager.GetString("AA0010012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Array Difinition..
        /// </summary>
        internal static string AA0010013 {
            get {
                return ResourceManager.GetString("AA0010013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Position Vector Definition..
        /// </summary>
        internal static string AA0010014 {
            get {
                return ResourceManager.GetString("AA0010014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posiotion Vector Parameters Must be of type flaot..
        /// </summary>
        internal static string AA0010015 {
            get {
                return ResourceManager.GetString("AA0010015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Point Definition..
        /// </summary>
        internal static string AA0010016 {
            get {
                return ResourceManager.GetString("AA0010016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For loop only accepts integers..
        /// </summary>
        internal static string AA0010017 {
            get {
                return ResourceManager.GetString("AA0010017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Speed Value..
        /// </summary>
        internal static string AA0010018 {
            get {
                return ResourceManager.GetString("AA0010018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Continuity Value..
        /// </summary>
        internal static string AA0010019 {
            get {
                return ResourceManager.GetString("AA0010019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIN command only accepts Eular points..
        /// </summary>
        internal static string AA0010020 {
            get {
                return ResourceManager.GetString("AA0010020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unreachable Point detected..
        /// </summary>
        internal static string AA0010021 {
            get {
                return ResourceManager.GetString("AA0010021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions must be  boolean..
        /// </summary>
        internal static string AA0010022 {
            get {
                return ResourceManager.GetString("AA0010022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break must be used inside a loop Operatror..
        /// </summary>
        internal static string AA0010023 {
            get {
                return ResourceManager.GetString("AA0010023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue must be used inside a loop Operatror..
        /// </summary>
        internal static string AA0010024 {
            get {
                return ResourceManager.GetString("AA0010024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SelfTest Pruceduer ....
        /// </summary>
        internal static string AA0110001 {
            get {
                return ResourceManager.GetString("AA0110001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfTest started..
        /// </summary>
        internal static string AA0110002 {
            get {
                return ResourceManager.GetString("AA0110002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for other operation to be completed..
        /// </summary>
        internal static string AA0110003 {
            get {
                return ResourceManager.GetString("AA0110003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Beckhoff Controller ....
        /// </summary>
        internal static string AA0110004 {
            get {
                return ResourceManager.GetString("AA0110004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller has been Started..
        /// </summary>
        internal static string AA0110005 {
            get {
                return ResourceManager.GetString("AA0110005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start testing Drive(s) ....
        /// </summary>
        internal static string AA0110006 {
            get {
                return ResourceManager.GetString("AA0110006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive(s) is responding..
        /// </summary>
        internal static string AA0110007 {
            get {
                return ResourceManager.GetString("AA0110007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Drive(s) are ready to SwitchOn..
        /// </summary>
        internal static string AA0110008 {
            get {
                return ResourceManager.GetString("AA0110008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive(s) have Errors..
        /// </summary>
        internal static string AA0110009 {
            get {
                return ResourceManager.GetString("AA0110009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trying to clear erros..
        /// </summary>
        internal static string AA0110010 {
            get {
                return ResourceManager.GetString("AA0110010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Drive(s) Errors..
        /// </summary>
        internal static string AA0110011 {
            get {
                return ResourceManager.GetString("AA0110011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Drive(s) are ready to Move..
        /// </summary>
        internal static string AA0110012 {
            get {
                return ResourceManager.GetString("AA0110012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive(s) are Moving ....
        /// </summary>
        internal static string AA0110013 {
            get {
                return ResourceManager.GetString("AA0110013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive(s) are Safe..
        /// </summary>
        internal static string AA0110014 {
            get {
                return ResourceManager.GetString("AA0110014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple parameter registeration..
        /// </summary>
        internal static string AA1110001 {
            get {
                return ResourceManager.GetString("AA1110001", resourceCulture);
            }
        }
    }
}
